"""create order and product table also add relationship

Revision ID: 8015924bc903
Revises: 
Create Date: 2025-01-07 19:30:08.990349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8015924bc903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_orders_user_id', 'orders', 'users', ['user_id'], ['id'])
    op.add_column('products', sa.Column('order_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key('fk_products_order_id', 'products', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_order_id', 'products', type_='foreignkey')
    op.drop_column('products', 'order_id')
    op.drop_constraint('fk_orders_user_id', 'orders', type_='foreignkey')
    op.drop_column('orders', 'user_id')
    # ### end Alembic commands ###
